import { useEffect, useState } from 'react'
import { ChevronRight, Download, Link2, LoaderCircle, Plus, ShieldCheck, Trash2, Unlink, X } from 'lucide-react'
import { Card, SectionHeading } from '../components/Ui'
import { deleteRide, getOwnRides, saveRide, syncJerseyHistory, type LiveRide } from '../lib/supabaseData'
import { announceLiveDataChange } from '../lib/liveSeason'
import { getSupabaseAccessToken } from '../lib/supabaseAuth'
type Ride = { id: string; externalId?: string | null; title: string; distance: number; elevation: number; movingSeconds?: number | null; points: number; source: 'manual' | 'strava' }
type StravaActivity = { id: number; name?: string; type?: string; sport_type?: string; distance?: number; total_elevation_gain?: number; moving_time?: number; start_date?: string }
const mapRide = (ride: LiveRide): Ride => ({ id: ride.id, externalId: ride.external_id, title: ride.title, distance: ride.distance_m / 1000, elevation: ride.elevation_m, movingSeconds: ride.moving_time_s, points: ride.points, source: ride.source })
const cyclingTypes = new Set(['Ride', 'VirtualRide', 'EBikeRide', 'GravelRide'])
export function ActivityHub({ notify, userId }: { notify: (message: string) => void; userId?: string }) {
  const [rides, setRides] = useState<Ride[]>([]), [connected, setConnected] = useState(false), [manual, setManual] = useState(false), [detail, setDetail] = useState<Ride | null>(null), [importing, setImporting] = useState(false)
  const token = () => ({ Authorization: `Bearer ${getSupabaseAccessToken() || ''}` })
  const load = async () => { if (userId) setRides((await getOwnRides(userId)).map(mapRide)) }
  const status = async () => { const response = await fetch('/api/strava/status', { headers: token() }); const data = await response.json(); setConnected(Boolean(data.connected)) }
  useEffect(() => { void load(); void status() }, [userId])
  const save = async (title: string, distance: number, elevation: number, source: 'manual' | 'strava' = 'manual', extra: Partial<LiveRide> = {}) => { if (!userId) return; const points = Math.round(distance + elevation / 10); const groupId = localStorage.getItem(`velo-active-group:${userId}`); const ride = await saveRide({ user_id: userId, group_id: groupId, source, title, distance_m: Math.round(distance * 1000), elevation_m: elevation, points, started_at: new Date().toISOString(), ...extra }); if (groupId) void syncJerseyHistory(groupId).catch(() => undefined); return ride }
  const importStrava = async () => {
    if (!userId) return; setImporting(true)
    try {
      const response = await fetch('/api/strava/activities', { headers: token() }); const data = await response.json()
      if (!response.ok) throw new Error(data.error || 'Strava-Fahrten konnten nicht geladen werden.')
      const existing = new Set(rides.map(ride => ride.externalId).filter(Boolean)); const activities = (data.activities as StravaActivity[]).filter(activity => cyclingTypes.has(activity.type || '') || cyclingTypes.has(activity.sport_type || ''))
      let imported = 0
      for (const activity of activities) {
        const externalId = String(activity.id); if (existing.has(externalId)) continue
        await save(activity.name || 'Strava-Fahrt', (activity.distance || 0) / 1000, Math.round(activity.total_elevation_gain || 0), 'strava', { external_id: externalId, moving_time_s: activity.moving_time || null, started_at: activity.start_date || new Date().toISOString() }); imported++
      }
      await load(); announceLiveDataChange(); notify(imported ? `${imported} Strava-Fahrt${imported === 1 ? '' : 'en'} importiert.` : 'Keine neuen Radfahrten bei Strava gefunden.')
    } catch (error) { notify(error instanceof Error ? error.message : 'Strava-Import fehlgeschlagen.') } finally { setImporting(false) }
  }
  const remove = async () => { if (!detail) return; try { await deleteRide(detail.id); setRides(current => current.filter(ride => ride.id !== detail.id)); setDetail(null); announceLiveDataChange(); notify('Fahrt gelöscht.') } catch (error) { notify(error instanceof Error ? error.message : 'Fahrt konnte nicht gelöscht werden.') } }
  const connect = async () => { const response = await fetch('/api/strava/connect', { headers: token() }); const data = await response.json(); if (data.url) window.location.assign(data.url); else notify(data.error || 'Strava konnte nicht verbunden werden.') }
  return <div className="page activities-page"><Card className="strava-card"><div className="strava-logo">STRAVA</div><div className="strava-copy"><p className="eyebrow">DEIN AKTIVITÄTS-IMPORT</p><h2>{connected ? 'Strava ist verbunden' : 'Verbinde dein Strava'}</h2><p>Es werden nur deine Radfahrten importiert und deinem Konto zugeordnet.</p></div><div className="strava-action">{connected ? <><button onClick={() => void importStrava()} disabled={importing} className="primary-button">{importing ? <LoaderCircle className="spin" size={16}/> : <Download size={16}/>} {importing ? 'Import läuft…' : 'Fahrten importieren'}</button><button onClick={() => void fetch('/api/strava/disconnect', { method: 'POST', headers: token() }).then(() => setConnected(false))} className="text-button"><Unlink size={14}/> Strava trennen</button></> : <button onClick={() => void connect()} className="primary-button"><Link2 size={16}/> Mit Strava verbinden</button>}<small><ShieldCheck size={12}/> Sicher über Strava OAuth</small></div></Card><SectionHeading eyebrow="DEINE FAHRTEN" title="Aktivitäten" action={<button className="text-button" onClick={() => setManual(true)}><Plus size={15}/> Fahrt eintragen</button>}/>{rides.length ? <div className="ride-list">{rides.map(ride => <button className="ride-button" key={ride.id} onClick={() => setDetail(ride)}><Card className="ride-card"><div className="ride-map"/><div className="ride-main"><p className="eyebrow">{ride.source === 'manual' ? 'MANUELL' : 'STRAVA'}</p><h3>{ride.title}</h3><div><span>{ride.distance.toLocaleString('de-DE')} km</span><span>{ride.elevation.toLocaleString('de-DE')} hm</span></div></div><strong className="ride-points">+{ride.points}<small> PTS</small></strong><ChevronRight size={18}/></Card></button>)}</div> : <Card className="empty-inline"><Plus size={20}/><div><strong>Noch keine Fahrten.</strong><p>Verbinde Strava oder trage deine erste Fahrt ein.</p></div></Card>}{manual && <Manual onClose={() => setManual(false)} onSave={async (title, distance, elevation) => { try { await save(title, distance, elevation); await load(); setManual(false); announceLiveDataChange(); notify('Fahrt gespeichert.') } catch (error) { notify(error instanceof Error ? error.message : 'Fahrt konnte nicht gespeichert werden.') } }}/>} {detail && <div className="modal-backdrop group-modal"><section className="create-group"><button className="drawer-close" onClick={() => setDetail(null)}><X/></button><h2>{detail.title}</h2><p>{detail.distance} km · {detail.elevation} hm · +{detail.points} PTS</p><button className="secondary-button" onClick={() => void remove()}><Trash2 size={15}/> Fahrt löschen</button></section></div>}</div>
}
function Manual({ onClose, onSave }: { onClose: () => void; onSave: (title: string, distance: number, elevation: number) => void }) { const [name, setName] = useState('Sonntagsrunde'), [km, setKm] = useState(45), [hm, setHm] = useState(620); return <div className="modal-backdrop group-modal"><section className="create-group"><button className="drawer-close" onClick={onClose}><X/></button><h2>Fahrt hinzufügen</h2><label>Name der Fahrt<input value={name} onChange={event => setName(event.target.value)}/></label><label>Kilometer<input type="number" value={km} onChange={event => setKm(Number(event.target.value))}/></label><label>Höhenmeter<input type="number" value={hm} onChange={event => setHm(Number(event.target.value))}/></label><button className="primary-button" onClick={() => onSave(name, km, hm)}>Fahrt speichern</button></section></div> }
