import { useEffect, useState } from 'react'
import { CheckCircle2, Flag, Plus, Swords, X } from 'lucide-react'
import { Card, EmptyGuide } from '../components/Ui'
import { completeChallenge, createChallenge, getChallenges, getGroupMembers, getRides, notifyChallenge, updateChallengeStatus, type LiveChallenge, type LiveGroup, type LiveMember, type LiveRide } from '../lib/supabaseData'
import { announceLiveDataChange } from '../lib/liveSeason'
import type { Page } from '../App'
type Tab = 'overview' | 'pending' | 'accepted'
const progress = (challenge: LiveChallenge, riderId: string, rides: LiveRide[]) => { const relevant = rides.filter(ride => ride.user_id === riderId && new Date(ride.started_at) >= new Date(challenge.starts_at || challenge.created_at) && new Date(ride.started_at) <= new Date(challenge.ends_at)); return challenge.target_unit === 'hm' ? relevant.reduce((sum, ride) => sum + ride.elevation_m, 0) : relevant.reduce((sum, ride) => sum + ride.distance_m / 1000, 0) }
export function Challenges({ notify, userId, groups, onNavigate }: { notify: (message: string) => void; userId?: string; groups: LiveGroup[]; onNavigate: (page: Page) => void }) { const [items, setItems] = useState<LiveChallenge[]>([]), [members, setMembers] = useState<LiveMember[]>([]), [rides, setRides] = useState<LiveRide[]>([]), [planner, setPlanner] = useState(false), [tab, setTab] = useState<Tab>('overview'), [error, setError] = useState(''); const active = groups.find(group => group.id === (userId ? localStorage.getItem(`velo-active-group:${userId}`) : '')) || groups[0]
  const load = async () => { if (!active) return; const [challenges, nextMembers, nextRides] = await Promise.all([getChallenges(active.id), getGroupMembers(active.id), getRides(active.id)]); const activeChallenges = challenges.filter(item => item.status === 'accepted' && item.target_value); const finished = activeChallenges.filter(item => progress(item, item.challenger_id || item.creator_id, nextRides) >= Number(item.target_value) || progress(item, item.opponent_id, nextRides) >= Number(item.target_value)); if (finished.length) await Promise.all(finished.map(async item => { await completeChallenge(item.id); void notifyChallenge(item.id, 'completed') })); const current = finished.length ? await getChallenges(active.id) : challenges; setItems(current); setMembers(nextMembers); setRides(nextRides) }
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 15000); return () => window.clearInterval(timer) }, [active?.id])
  if (!active) return <div className="page"><EmptyGuide icon={<Swords size={24}/>} eyebrow="CHALLENGES" title="Dein erstes Duell beginnt hier" text="Erstelle zuerst eine Gruppe und lade mindestens einen Freund ein." preview={<div className="guide-challenge"><b>Du</b><i/><b>Freund</b></div>} action={<button className="primary-button" onClick={() => onNavigate('group')}>Gruppe öffnen</button>}/></div>
  const visible = items.filter(item => tab === 'overview' ? ['pending', 'accepted', 'completed'].includes(item.status) : tab === 'pending' ? item.status === 'pending' : item.status === 'accepted')
  const create = async (title: string, goal: string, opponent: string, targetValue: number, targetUnit: 'km' | 'hm') => {
    if (!userId || !opponent || !active) return
    if (!members.some(member => member.user_id === opponent)) {
      const message = 'Dieser Fahrer ist nicht mehr Mitglied deiner aktiven Gruppe.'
      setError(message)
      notify(message)
      return
    }
    try {
      const challenge = await createChallenge({ group_id: active.id, challenger_id: userId, creator_id: userId, opponent_id: opponent, title, goal, challenge_type: 'free', target_value: targetValue, target_unit: targetUnit, reward: '100 Saisonpunkte', ends_at: new Date(Date.now() + 5 * 86400000).toISOString() })
      void notifyChallenge(challenge.id, 'requested')
      setPlanner(false)
      setTab('pending')
      await load()
      announceLiveDataChange()
      notify('Challenge an deinen Gegner gesendet.')
    } catch (reason) {
      const message = reason instanceof Error ? reason.message : 'Challenge konnte nicht geplant werden.'
      setError(message)
      notify(message)
    }
  }
  const change = async (item: LiveChallenge, status: LiveChallenge['status']) => { try { await updateChallengeStatus(item.id, status); if (status === 'accepted') void notifyChallenge(item.id, 'accepted'); await load(); notify(status === 'accepted' ? 'Challenge angenommen. Der Fortschritt zählt ab jetzt.' : 'Challenge abgebrochen.') } catch (reason) { notify(reason instanceof Error ? reason.message : 'Status konnte nicht gespeichert werden.') } }
  return <div className="page"><div className="duel-hero"><div><p className="eyebrow">DEINE GRUPPEN-DUELLE</p><h2>{active.name}</h2><p>Fortschritt wird direkt aus euren Fahrten berechnet.</p></div><span className="live-dot">LIVE</span></div><div className="challenge-actions"><button className="primary-button" onClick={() => { setError(''); setPlanner(true) }}><Plus size={16}/> Challenge planen</button></div><div className="challenge-tabs"><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>Übersicht</button><button className={tab === 'pending' ? 'active' : ''} onClick={() => setTab('pending')}>Ausstehend</button><button className={tab === 'accepted' ? 'active' : ''} onClick={() => setTab('accepted')}>Angenommen</button></div>{error && <Card className="empty-challenge-tab"><h3>Challenge konnte nicht erstellt werden</h3><p>{error}</p></Card>}{visible.length ? <div className="ride-list">{visible.map(item => <ChallengeCard key={item.id} item={item} userId={userId} rides={rides} onChange={change}/>)}</div> : <Card className="empty-challenge-tab"><Swords size={22}/><h3>Hier ist noch nichts geplant.</h3><p>Erstelle eine Challenge oder lade zuerst einen Freund ein.</p></Card>}{planner && <Planner members={members.filter(member => member.user_id !== userId)} onClose={() => setPlanner(false)} onCreate={create}/>}</div> }
function ChallengeCard({ item, userId, rides, onChange }: { item: LiveChallenge; userId?: string; rides: LiveRide[]; onChange: (item: LiveChallenge, status: LiveChallenge['status']) => void }) { const mine = userId === item.opponent_id ? item.opponent_id : item.challenger_id || item.creator_id, other = mine === item.opponent_id ? item.challenger_id || item.creator_id : item.opponent_id, target = Number(item.target_value || 0), own = progress(item, mine, rides), rival = progress(item, other, rides), unit = item.target_unit === 'hm' ? 'hm' : 'km', complete = item.status === 'completed'; return <Card className="ride-card"><div className="ride-main"><p className="eyebrow">{complete ? 'ABGESCHLOSSEN' : item.status === 'accepted' ? 'LIVE · ANGENOMMEN' : 'AUSSTEHEND'} · BIS {new Date(item.ends_at).toLocaleDateString('de-DE')}</p><h3>{item.title}</h3><div><span>{item.goal}</span><span>{item.reward || '100 Saisonpunkte'}</span></div>{item.status !== 'pending' && target > 0 && <div className="challenge-progress"><span>Du: {Math.round(own)} / {target} {unit}</span><i><b style={{ width: `${Math.min(100, own / target * 100)}%` }}/></i><span>Gegner: {Math.round(rival)} / {target} {unit}</span><i><b style={{ width: `${Math.min(100, rival / target * 100)}%` }}/></i></div>}</div>{complete ? <span className="detail-status"><CheckCircle2 size={14}/> Ziel erreicht</span> : item.opponent_id === userId && item.status === 'pending' ? <button className="primary-button" onClick={() => onChange(item, 'accepted')}>Annehmen</button> : (item.challenger_id || item.creator_id) === userId && item.status === 'pending' ? <button className="secondary-button" onClick={() => onChange(item, 'cancelled')}>Abbrechen</button> : <Flag className="ride-chevron"/>}</Card> }
function Planner({ members, onClose, onCreate }: { members: LiveMember[]; onClose: () => void; onCreate: (title: string, goal: string, opponent: string, target: number, unit: 'km' | 'hm') => void }) { const [title, setTitle] = useState('Ortsschild-Sprint'), [goal, setGoal] = useState('Wer zuerst 50 km sammelt'), [opponent, setOpponent] = useState(members[0]?.user_id || ''); const setup = goal.includes('Höhenmeter') ? [1000, 'hm'] as const : [50, 'km'] as const; return <div className="modal-backdrop planner-wrap"><section className="planner-card"><button className="drawer-close" onClick={onClose}><X size={19}/></button><p className="eyebrow">FREIE CHALLENGE</p><h2>Neues Duell planen</h2>{members.length ? <><label>Name<input value={title} onChange={event => setTitle(event.target.value)}/></label><label>Ziel<select value={goal} onChange={event => setGoal(event.target.value)}><option>Wer zuerst 50 km sammelt</option><option>Wer zuerst 1.000 Höhenmeter sammelt</option></select></label><label>Gegner<select value={opponent} onChange={event => setOpponent(event.target.value)}>{members.map(member => <option key={member.user_id} value={member.user_id}>{member.profiles?.display_name || 'Rider'}</option>)}</select></label><button className="primary-button wide" onClick={() => onCreate(title, goal, opponent, setup[0], setup[1])}>Challenge anfragen</button></> : <p className="empty-copy">Lade zuerst mindestens einen Freund in deine Gruppe ein.</p>}</section></div> }
