import { useState } from 'react'
import { Check, Clock3, Mountain, Swords, Trophy, X, Zap } from 'lucide-react'
import { Card, SectionHeading } from '../components/Ui'
type Challenge={title:string;opponent:string;goal:string;reward:string;jersey:string;days:string}
const active:Challenge={title:'Königsetappe',opponent:'Max',goal:'Wer zuerst 1.000 Höhenmeter sammelt',reward:'150 Saisonpunkte',jersey:'Gelbes Trikot · Gesamtwertung',days:'Noch 3 Tage'}
const invite:Challenge={title:'Sprint durch Corvara',opponent:'Lukas',goal:'Höchste Durchschnittsgeschwindigkeit',reward:'100 Sprintpunkte',jersey:'Grünes Sprinttrikot',days:'4 Tage Zeit'}
export function Challenges({notify}:{notify:(m:string)=>void}){const[detail,setDetail]=useState<Challenge|null>(null),[accepted,setAccepted]=useState(false);return <div className="page"><div className="duel-hero"><div><p className="eyebrow">AKTIVE DUELLE</p><h2>Dein nächster Schlagabtausch.</h2></div><span className="live-dot">LIVE</span></div><button className="duel-click" onClick={()=>setDetail(active)}><Card className="duel-card"><div className="duel-head"><div className="duel-rider"><span className="rider-avatar yellow-avatar">P</span><b>Philipp</b></div><Swords className="swords" size={27}/><div className="duel-rider right"><span className="rider-avatar red-avatar">M</span><b>Max</b></div></div><div className="duel-name"><span><Trophy size={16}/></span><div><h3>{active.title}</h3><p>{active.goal}</p></div></div><div className="progress-players"><Progress name="Philipp" value={80} color="yellow"/><Progress name="Max" value={90} color="red"/></div><div className="duel-footer"><span><Clock3 size={16}/> {active.days}</span><span className="detail-link">Insights ansehen</span></div></Card></button><SectionHeading eyebrow="EINGEHENDE ANFRAGE" title="Neue Challenge"/><Card className="request-card"><span className="rider-avatar green-avatar">L</span><div><h3>Lukas fordert dich heraus</h3><p>{invite.title} · {invite.days}</p></div><button onClick={()=>{setAccepted(true);setDetail(invite);notify('Challenge angenommen.')}} className={accepted?'accepted-button':'primary-button'}>{accepted?<><Check size={16}/> Angenommen</>:'Annehmen'}</button></Card>{detail&&<ChallengeDetail challenge={detail} accepted={accepted} onClose={()=>setDetail(null)}/>}</div>}
function Progress({name,value,color}:{name:string;value:number;color:string}){return <div className="progress-player"><div><b>{name}</b><strong>{value}%</strong></div><div className="progress-track"><i className={color} style={{width:`${value}%`}}/></div></div>}
function ChallengeDetail({challenge,accepted,onClose}:{challenge:Challenge;accepted:boolean;onClose:()=>void}){return <div className="modal-backdrop planner-wrap"><section className="planner-card"><button className="drawer-close" onClick={onClose}><X size={19}/></button><p className="eyebrow">{accepted?'CHALLENGE ANGENOMMEN':'CHALLENGE-INSIGHTS'}</p><h2>{challenge.title}</h2><div className="challenge-insights"><div><span>Gegner</span><b>{challenge.opponent}</b></div><div><span>Ziel</span><b>{challenge.goal}</b></div><div><span>Belohnung</span><b>{challenge.reward}</b></div><div><span>Wertung</span><b>{challenge.jersey}</b></div></div><p className="insight-note"><Mountain size={15}/> Diese Challenge kann die Trikotwertung direkt beeinflussen.</p><button className="primary-button wide" onClick={onClose}><Zap size={16}/> {accepted?'Zur Challenge':'Verstanden'}</button></section></div>}
