import { useState } from 'react'
import { ArrowRight, ChevronRight, Crown, Flame, Mountain, Trophy, X, Zap } from 'lucide-react'
import type { Page } from '../App'
import { Card, EmptyGuide, Jersey, SectionHeading } from '../components/Ui'
import type { ElementType } from 'react'
export function Dashboard({onNavigate,empty=false}:{onNavigate:(page:Page)=>void;empty?:boolean}){const[activityOpen,setActivityOpen]=useState(false),[statsOpen,setStatsOpen]=useState(false);if(empty)return <div className="page dashboard-page"><EmptyGuide icon={<Trophy size={24}/>} eyebrow="DEIN START" title="Deine Saison kann beginnen" text="Synchronisiere deine erste Fahrt oder tritt einer Gruppe bei. Danach erscheinen hier deine echten Kilometer, Höhenmeter und Trikotziele." preview={<div className="guide-ranking"><div><b>0</b><span>Saisonpunkte</span><strong>NOCH OFFEN</strong></div><div><b>1.</b><span>Fahrt hinzufügen</span><strong>LOS GEHT'S</strong></div></div>} action={<button className="primary-button" onClick={()=>onNavigate('activities')}>Erste Fahrt hinzufügen</button>}/></div>;return <div className="page dashboard-page"><div className="dashboard-grid"><Card className="leader-card"><div className="leader-noise"/><div className="leader-copy"><p className="eyebrow">AKTUELLES TRIKOT</p><h2>Gelbes Trikot</h2><p className="muted">Du führst die Alpine Cycling League.</p><div className="leader-name"><Jersey/><div><strong>Philipp</strong><span>Gesamtführender</span></div></div></div><div className="leader-points"><strong>2.450</strong><span>Saisonpunkte</span><em><Crown size={14}/> RANG #1</em></div></Card><Card className="challenge-hero"><div className="route-lines"/><div className="challenge-content"><p className="eyebrow">NÄCHSTE HERAUSFORDERUNG</p><h2><Mountain size={22}/> Alpenstraße König</h2><div className="challenge-numbers"><span><b>5,4</b> km</span><span><b>420</b> hm</span><span><b>19:05</b> deine Zeit</span></div><button onClick={()=>onNavigate('challenges')} className="primary-button">Challenge ansehen <ArrowRight size={17}/></button></div><div className="best-time"><span>BESTE ZEIT</span><b>18:32</b><small>Max · 2026</small></div></Card></div><SectionHeading eyebrow="DEINE LEISTUNG" title="Saisonübersicht" action={<button onClick={()=>setStatsOpen(true)} className="text-button">Alle Statistiken <ChevronRight size={16}/></button>}/><div className="stats-grid">{stats.map(({value,label,Icon})=><Card className="stat-card" key={label}><span className="stat-icon"><Icon size={19}/></span><strong>{value}</strong><span>{label}</span></Card>)}</div><SectionHeading eyebrow="IM RÜCKSPIEGEL" title="Letzte Aktivitäten"/><button className="activity-click" onClick={()=>setActivityOpen(true)}><Card className="activity"><div className="activity-icon"><Mountain size={19}/></div><div><strong>Mendelpass Attack</strong><p>Heute · 42,8 km · 1.120 hm</p></div><b>+180 <small>PTS</small></b><span className="rank-pill">#2 Berg</span></Card></button>{activityOpen&&<ActivityDetail onClose={()=>setActivityOpen(false)}/>} {statsOpen&&<StatsDetail onClose={()=>setStatsOpen(false)}/>}</div>}
function StatsDetail({onClose}:{onClose:()=>void}){return <div className="modal-backdrop" onClick={onClose}><section className="activity-detail" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}><X size={18}/></button><p className="eyebrow">SAISONSTATISTIK 2026</p><h2>Deine Leistungsübersicht</h2><div className="ride-detail-grid">{[['1.850 km','Gesamtdistanz'],['32.500 hm','Höhenmeter'],['78:42 h','Fahrzeit'],['142 km','Längste Ausfahrt'],['23,6 km/h','Ø Geschwindigkeit'],['2.450 PTS','Saisonpunkte']].map(([value,label])=><div key={label}><b>{value}</b><span>{label}</span></div>)}</div><div className="points-breakdown"><p>WOHER KOMMEN DEINE PUNKTE?</p><div><span><Zap size={15}/> Kilometer</span><b>+1.850 PTS</b></div><div><span><Mountain size={15}/> Höhenmeter</span><b>+3.250 PTS</b></div><div><span><Trophy size={15}/> Challenges & Podien</span><b>+1.160 PTS</b></div></div></section></div>}
function ActivityDetail({onClose}:{onClose:()=>void}){return <div className="modal-backdrop" onClick={onClose}><section className="activity-detail" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}><X size={18}/></button><p className="eyebrow">FAHRT-INSIGHTS · HEUTE</p><h2>Mendelpass Attack</h2><div className="ride-detail-grid"><div><b>42,8 km</b><span>Distanz</span></div><div><b>1.120 hm</b><span>Höhenmeter</span></div><div><b>1:46:18</b><span>Fahrzeit</span></div><div><b>24,2 km/h</b><span>Ø Geschwindigkeit</span></div></div></section></div>}
const stats:{value:string;label:string;Icon:ElementType}[]=[{value:'1.850',label:'Kilometer',Icon:BikeIcon},{value:'32.500',label:'Höhenmeter',Icon:Mountain},{value:'14',label:'Siege',Icon:Trophy},{value:'27',label:'Podiumsplätze',Icon:Flame}]
function BikeIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="5.5" cy="17.5" r="3.5"/><circle cx="18.5" cy="17.5" r="3.5"/><path d="M5.5 17.5 9 8h4l2 9.5M8 12h7M10 5h4"/></svg>}
