import { useState } from 'react'
import { ArrowRight, ChevronRight, Crown, Mountain, Trophy, X, Zap } from 'lucide-react'
import type { Page } from '../App'
import { Card, EmptyGuide, Jersey, SectionHeading } from '../components/Ui'
import type { SeasonStats } from '../lib/liveSeason'

const number = (value: number) => Math.round(value).toLocaleString('de-DE')
const duration = (seconds: number) => seconds ? `${Math.floor(seconds / 3600)}:${String(Math.floor(seconds % 3600 / 60)).padStart(2, '0')} h` : '—'

export function Dashboard({ onNavigate, empty = false, stats, user, hasGroup }: { onNavigate: (page: Page) => void; empty?: boolean; stats: SeasonStats; user: string; hasGroup: boolean }) {
  const [statsOpen, setStatsOpen] = useState(false)
  if (empty) return <div className="page dashboard-page"><EmptyGuide icon={<Trophy size={24}/>} eyebrow="DEIN START" title="Deine Saison kann beginnen" text="Synchronisiere deine erste Fahrt oder trage sie manuell ein. Danach erscheinen hier deine echten Kilometer, Höhenmeter und Punkte." preview={<div className="guide-ranking"><div><b>0</b><span>Saisonpunkte</span><strong>NOCH OFFEN</strong></div><div><b>1.</b><span>Fahrt hinzufügen</span><strong>LOS GEHT'S</strong></div></div>} action={<button className="primary-button" onClick={() => onNavigate('activities')}>Erste Fahrt hinzufügen</button>}/></div>
  const hasJersey = hasGroup && stats.rides.length > 0
  const latest = stats.rides[0]
  return <div className="page dashboard-page"><div className="dashboard-grid"><Card className="leader-card"><div className="leader-noise"/><div className="leader-copy"><p className="eyebrow">{hasJersey ? 'AKTUELLES TRIKOT' : 'DEINE SAISON'}</p><h2>{hasJersey ? 'Gelbes Trikot' : 'Punkte gesammelt'}</h2><p className="muted">{hasJersey ? 'In deiner Gruppe führst du aktuell die Gesamtwertung.' : 'Erstelle oder tritt einer Gruppe bei, um Trikots zu gewinnen.'}</p><div className="leader-name"><Jersey type={hasJersey ? 'yellow' : 'plain'}/><div><strong>{user}</strong><span>{hasJersey ? 'Gesamtführender' : 'Saisonstart'}</span></div></div></div><div className="leader-points"><strong>{number(stats.points)}</strong><span>Saisonpunkte</span><em><Crown size={14}/> {hasJersey ? 'RANG #1' : `${stats.rides.length} FAHRT${stats.rides.length === 1 ? '' : 'EN'}`}</em></div></Card><Card className="challenge-hero"><div className="route-lines"/><div className="challenge-content"><p className="eyebrow">NÄCHSTER SCHRITT</p><h2><Mountain size={22}/>{hasGroup ? 'Deine Gruppe einladen' : 'Gemeinsam starten'}</h2><div className="challenge-numbers"><span><b>{number(stats.kilometers)}</b> km</span><span><b>{number(stats.elevation)}</b> hm</span><span><b>{number(stats.points)}</b> PTS</span></div><button onClick={() => onNavigate(hasGroup ? 'challenges' : 'group')} className="primary-button">{hasGroup ? 'Challenges ansehen' : 'Gruppe erstellen'} <ArrowRight size={17}/></button></div></Card></div><SectionHeading eyebrow="DEINE LEISTUNG" title="Saisonübersicht" action={<button onClick={() => setStatsOpen(true)} className="text-button">Alle Statistiken <ChevronRight size={16}/></button>}/><div className="stats-grid"><Metric value={`${number(stats.kilometers)} km`} label="Kilometer"/><Metric value={`${number(stats.elevation)} hm`} label="Höhenmeter"/><Metric value={duration(stats.movingSeconds)} label="Fahrzeit"/><Metric value={`${number(stats.longestKilometers)} km`} label="Längste Ausfahrt"/></div><SectionHeading eyebrow="IM RÜCKSPIEGEL" title="Letzte Aktivitäten"/>{latest && <button className="activity-click" onClick={() => onNavigate('activities')}><Card className="activity"><div className="activity-icon"><Mountain size={19}/></div><div><strong>{latest.title}</strong><p>{(latest.distance_m / 1000).toLocaleString('de-DE')} km · {latest.elevation_m.toLocaleString('de-DE')} hm</p></div><b>+{latest.points} <small>PTS</small></b></Card></button>}{statsOpen && <StatsDetail stats={stats} onClose={() => setStatsOpen(false)}/>}</div>
}
function Metric({ value, label }: { value: string; label: string }) { return <Card className="stat-card"><span className="stat-icon"><Zap size={19}/></span><strong>{value}</strong><span>{label}</span></Card> }
function StatsDetail({ stats, onClose }: { stats: SeasonStats; onClose: () => void }) { return <div className="modal-backdrop" onClick={onClose}><section className="activity-detail" onClick={event => event.stopPropagation()}><button className="modal-close" onClick={onClose}><X size={18}/></button><p className="eyebrow">SAISONSTATISTIK 2026</p><h2>Deine Leistungsübersicht</h2><div className="ride-detail-grid">{[[`${number(stats.kilometers)} km`, 'Gesamtdistanz'], [`${number(stats.elevation)} hm`, 'Höhenmeter'], [duration(stats.movingSeconds), 'Fahrzeit'], [`${number(stats.longestKilometers)} km`, 'Längste Ausfahrt'], [`${number(stats.points)} PTS`, 'Saisonpunkte'], [String(stats.rides.length), 'Fahrten']].map(([value, label]) => <div key={label}><b>{value}</b><span>{label}</span></div>)}</div><div className="points-breakdown"><p>WOHER KOMMEN DEINE PUNKTE?</p><div><span><Zap size={15}/> Kilometer</span><b>+{number(stats.kilometers)} PTS</b></div><div><span><Mountain size={15}/> Höhenmeter</span><b>+{number(stats.elevation / 10)} PTS</b></div><div className="points-total"><span><Trophy size={15}/> Gesamt</span><b>+{number(stats.points)} PTS</b></div></div></section></div> }
