import { useEffect, useState } from 'react'
import { Check, Copy, Crown, Link2, Plus, QrCode, Settings2, Share2, Users, X } from 'lucide-react'
import type { Page } from '../App'
import { Card, Jersey, SectionHeading } from '../components/Ui'

type Group = { id:string; name:string; invite:string; created:string }
const storageKey='velo-test-groups'

export function GroupHub({ notify, onNavigate }: { notify:(m:string)=>void; onNavigate:(p:Page)=>void }) {
  const [groups,setGroups]=useState<Group[]>([])
  const [active,setActive]=useState<Group | null>(null)
  const [create,setCreate]=useState(false)
  const [copied,setCopied]=useState(false)
  const [showQr,setShowQr]=useState(false)
  const [showMembers,setShowMembers]=useState(false)
  useEffect(()=>{const saved=localStorage.getItem(storageKey);if(saved){const all=JSON.parse(saved) as Group[];setGroups(all);setActive(all[0]??null)}},[])
  const save=(group:Group)=>{const next=[group,...groups];setGroups(next);setActive(group);localStorage.setItem(storageKey,JSON.stringify(next));setCreate(false);notify(`„${group.name}“ erstellt. Dein Einladungslink ist bereit.`)}
  const inviteUrl=active?`${location.origin}/join/${active.invite}`:''
  const copy=async()=>{if(!active)return;try{await navigator.clipboard?.writeText(inviteUrl)}finally{setCopied(true);notify('Einladungslink kopiert.');window.setTimeout(()=>setCopied(false),1800)}}
  if(!active)return <div className="page empty-page"><Card className="empty-state"><span><Users size={31}/></span><p className="eyebrow">TESTPHASE STARTEN</p><h2>Deine erste Gruppe ist noch leer.</h2><p>Erstelle eine private Gruppe und lade deine Freunde per Link ein. Danach startet eure Saison ohne Demo-Daten.</p><button className="primary-button" onClick={()=>setCreate(true)}><Plus size={16}/> Gruppe erstellen</button></Card>{create&&<CreateGroup onClose={()=>setCreate(false)} onCreate={save}/>}</div>
  return <div className="page"><Card className="group-hero"><div className="group-emblem"><Crown size={27}/></div><div><p className="eyebrow">PRIVATE GRUPPE · 1 MITGLIED</p><h2>{active.name}</h2><p>Testphase · nur für Mitglieder sichtbar.</p></div><button onClick={()=>setCreate(true)} className="group-switch"><Plus size={16}/> Gruppe</button></Card>{groups.length>1&&<div className="group-switcher">{groups.map(g=><button className={g.id===active.id?'active':''} onClick={()=>setActive(g)} key={g.id}>{g.name}</button>)}</div>}<div className="group-grid"><Card className="invite-card"><div><p className="eyebrow">FREUNDE EINLADEN</p><h3>Gemeinsam in die Saison.</h3><p>Jeder mit diesem Link kann deiner privaten Gruppe beitreten.</p></div><div className="invite-link"><Link2 size={16}/><span>…/join/{active.invite}</span><button aria-label="Einladungslink kopieren" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><div className="invite-actions"><button onClick={copy} className="primary-button"><Share2 size={15}/> Link teilen</button><button onClick={()=>setShowQr(true)} className="secondary-button"><QrCode size={16}/> QR-Code</button></div></Card><Card className="members-card"><div className="member-heading"><h3>Mitglieder</h3><button aria-label="Mitglieder verwalten" onClick={()=>setShowMembers(true)}><Settings2 size={16}/></button></div><div className="member"><Jersey type="yellow" small/><strong>Philipp</strong><span>Admin</span></div><p className="member-empty">Lade deine Freunde ein — sie erscheinen nach dem Beitritt hier.</p><button className="text-button" onClick={()=>setShowMembers(true)}>Mitglieder verwalten</button></Card></div><SectionHeading eyebrow="SICHTBAR NUR FÜR DIE GRUPPE" title="Gruppenfeed" action={<button className="text-button" onClick={()=>onNavigate('activities')}>Fahrten ansehen</button>}/><Card className="feed-empty"><Users size={22}/><div><strong>Der Gruppenfeed ist bereit.</strong><p>Die erste synchronisierte oder manuell eingetragene Fahrt erscheint hier.</p></div></Card><SectionHeading eyebrow="TRANSPARENT & EINFACH" title="Saisonregeln"/><Card className="rules-card"><Rule label="Kilometer" points="1 PTS / km"/><Rule label="Höhenmeter" points="1 PTS / 10 hm"/><Rule label="Segment-Podium" points="100 · 60 · 30 PTS"/><Rule label="Challenge-Sieg" points="150 PTS"/><button onClick={()=>notify('Regel-Editor folgt im nächsten Ausbau.')} className="secondary-button">Regeln ansehen</button></Card>{create&&<CreateGroup onClose={()=>setCreate(false)} onCreate={save}/>} {showQr&&<QrModal inviteUrl={inviteUrl} onCopy={copy} onClose={()=>setShowQr(false)}/>} {showMembers&&<MembersModal onInvite={copy} onClose={()=>setShowMembers(false)}/>}</div>
}
function Rule({label,points}:{label:string;points:string}){return <div><span>{label}</span><b>{points}</b></div>}
function QrModal({inviteUrl,onCopy,onClose}:{inviteUrl:string;onCopy:()=>void;onClose:()=>void}){const source=`https://api.qrserver.com/v1/create-qr-code/?size=320x320&margin=12&data=${encodeURIComponent(inviteUrl)}`;return <div className="modal-backdrop" onClick={onClose}><section className="share-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="QR-Code schließen" onClick={onClose}><X size={18}/></button><p className="eyebrow">EINLADUNG SCANNEN</p><h2>Direkt in deine Gruppe</h2><img className="invite-qr" src={source} alt="Scanbarer QR-Code für den Gruppenbeitritt"/><p>Mit der Handy-Kamera scannen oder den Link direkt teilen.</p><button className="primary-button" onClick={onCopy}><Copy size={16}/> Einladungslink kopieren</button></section></div>}
function MembersModal({onInvite,onClose}:{onInvite:()=>void;onClose:()=>void}){return <div className="modal-backdrop" onClick={onClose}><section className="share-modal members-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Mitgliederverwaltung schließen" onClick={onClose}><X size={18}/></button><p className="eyebrow">MITGLIEDERVERWALTUNG</p><h2>Deine Testgruppe</h2><div className="member manager-member"><Jersey type="yellow" small/><strong>Philipp</strong><span>Admin</span></div><div className="member-management-note"><Users size={18}/><p>Aktuell bist du allein in der Gruppe. Neue Mitglieder treten über deinen Einladungslink bei und werden danach hier angezeigt.</p></div><button className="primary-button" onClick={onInvite}><Share2 size={16}/> Freund einladen</button></section></div>}
function CreateGroup({onClose,onCreate}:{onClose:()=>void;onCreate:(group:Group)=>void}){const [name,setName]=useState('');const create=()=>{const clean=name.trim();if(!clean)return;onCreate({id:crypto.randomUUID(),name:clean,invite:crypto.randomUUID().slice(0,8),created:new Date().toISOString()})};return <div className="modal-backdrop group-modal"><section className="create-group"><p className="eyebrow">NEUE PRIVATE GRUPPE</p><h2>Gruppe erstellen</h2><label>Gruppenname<input value={name} placeholder="z. B. Wochenend-Racer" onChange={e=>setName(e.target.value)}/></label><label>Saison<select><option>Saison 2026</option><option>Herbst-Cup 2026</option></select></label><label className="toggle-row"><span>Eintritt nur per Link</span><input type="checkbox" defaultChecked/></label><div><button onClick={onClose} className="secondary-button">Abbrechen</button><button disabled={!name.trim()} onClick={create} className="primary-button">Erstellen</button></div></section></div>}
