import { useEffect, useState } from 'react'
import { Check, Copy, Crown, Link2, LoaderCircle, Plus, QrCode, Settings2, Share2, Users, X } from 'lucide-react'
import type { Page } from '../App'
import { Card, Jersey, SectionHeading } from '../components/Ui'
import { createGroup, getGroupMembers, getGroups, joinGroup, type LiveGroup, type LiveMember } from '../lib/supabaseData'

export function GroupHub({ userId, userName, notify, onNavigate }: { userId?: string; userName: string; notify:(m:string)=>void; onNavigate:(p:Page)=>void }) {
  const [groups,setGroups]=useState<LiveGroup[]>([]), [active,setActive]=useState<LiveGroup | null>(null), [members,setMembers]=useState<LiveMember[]>([])
  const [create,setCreate]=useState(false), [copied,setCopied]=useState(false), [showQr,setShowQr]=useState(false), [showMembers,setShowMembers]=useState(false), [loading,setLoading]=useState(true)
  const load=async()=>{ if(!userId){setLoading(false);return} try { const all=await getGroups();setGroups(all);setActive(current=>all.find(group=>group.id===current?.id)||all[0]||null) } catch(error){notify(error instanceof Error?error.message:'Gruppen konnten nicht geladen werden.')} finally {setLoading(false)} }
  useEffect(()=>{void load()},[userId])
  useEffect(()=>{if(!active)return;localStorage.setItem(`velo-active-group:${userId}`,active.id);void getGroupMembers(active.id).then(setMembers).catch(()=>setMembers([]))},[active?.id,userId])
  useEffect(()=>{const code=new URLSearchParams(location.search).get('join');if(!code||!userId)return;void joinGroup(code).then(()=>{history.replaceState(null,'',location.pathname);notify('Du bist der Gruppe beigetreten.');return load()}).catch(error=>notify(error instanceof Error?error.message:'Einladungslink ungültig.'))},[userId])
  const save=async(name:string)=>{if(!userId)return;try { const group=await createGroup(name,userId);setGroups(current=>[group,...current]);setActive(group);setCreate(false);notify(`„${group.name}“ erstellt. Dein Einladungslink ist bereit.`)}catch(error){notify(error instanceof Error?error.message:'Gruppe konnte nicht erstellt werden.')}}
  const inviteUrl=active?`${location.origin}${location.pathname}?join=${active.invite_code}`:''
  const copy=async()=>{if(!active)return;try{await navigator.clipboard?.writeText(inviteUrl)}finally{setCopied(true);notify('Einladungslink kopiert.');window.setTimeout(()=>setCopied(false),1800)}}
  if(loading)return <div className="page empty-page"><Card className="empty-state"><LoaderCircle className="spin" size={26}/><h2>Gruppen werden geladen…</h2></Card></div>
  if(!active)return <div className="page empty-page"><Card className="empty-state"><span><Users size={31}/></span><p className="eyebrow">TESTPHASE STARTEN</p><h2>Deine erste Gruppe ist noch leer.</h2><p>Erstelle eine private Gruppe und lade deine Freunde per Link ein. Danach startet eure Saison ohne Demo-Daten.</p><button className="primary-button" onClick={()=>setCreate(true)}><Plus size={16}/> Gruppe erstellen</button></Card>{create&&<CreateGroup onClose={()=>setCreate(false)} onCreate={save}/>}</div>
  return <div className="page"><Card className="group-hero"><div className="group-emblem"><Crown size={27}/></div><div><p className="eyebrow">PRIVATE GRUPPE · {members.length} {members.length===1?'MITGLIED':'MITGLIEDER'}</p><h2>{active.name}</h2><p>Testphase · nur für Mitglieder sichtbar.</p></div><button onClick={()=>setCreate(true)} className="group-switch"><Plus size={16}/> Gruppe</button></Card>{groups.length>1&&<div className="group-switcher">{groups.map(g=><button className={g.id===active.id?'active':''} onClick={()=>setActive(g)} key={g.id}>{g.name}</button>)}</div>}<div className="group-grid"><Card className="invite-card"><div><p className="eyebrow">FREUNDE EINLADEN</p><h3>Gemeinsam in die Saison.</h3><p>Jeder mit diesem Link kann deiner privaten Gruppe beitreten.</p></div><div className="invite-link"><Link2 size={16}/><span>…?join={active.invite_code}</span><button aria-label="Einladungslink kopieren" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><div className="invite-actions"><button onClick={copy} className="primary-button"><Share2 size={15}/> Link teilen</button><button onClick={()=>setShowQr(true)} className="secondary-button"><QrCode size={16}/> QR-Code</button></div></Card><Card className="members-card"><div className="member-heading"><h3>Mitglieder</h3><button aria-label="Mitglieder verwalten" onClick={()=>setShowMembers(true)}><Settings2 size={16}/></button></div>{members.slice(0,3).map(member=><div className="member" key={member.user_id}><Jersey type="yellow" small/><strong>{member.profiles?.display_name||'Rider'}</strong><span>{member.role==='admin'?'Admin':'Mitglied'}</span></div>)}<p className="member-empty">Lade deine Freunde ein — sie erscheinen nach dem Beitritt hier.</p><button className="text-button" onClick={()=>setShowMembers(true)}>Mitglieder verwalten</button></Card></div><SectionHeading eyebrow="SICHTBAR NUR FÜR DIE GRUPPE" title="Gruppenfeed" action={<button className="text-button" onClick={()=>onNavigate('activities')}>Fahrten ansehen</button>}/><Card className="feed-empty"><Users size={22}/><div><strong>Der Gruppenfeed ist bereit.</strong><p>Die erste synchronisierte oder manuell eingetragene Fahrt erscheint hier.</p></div></Card><SectionHeading eyebrow="TRANSPARENT & EINFACH" title="Saisonregeln"/><Card className="rules-card"><Rule label="Kilometer" points="1 PTS / km"/><Rule label="Höhenmeter" points="1 PTS / 10 hm"/><Rule label="Segment-Podium" points="100 · 60 · 30 PTS"/><Rule label="Challenge-Sieg" points="150 PTS"/></Card>{create&&<CreateGroup onClose={()=>setCreate(false)} onCreate={save}/>} {showQr&&<QrModal inviteUrl={inviteUrl} onCopy={copy} onClose={()=>setShowQr(false)}/>} {showMembers&&<MembersModal members={members} onInvite={copy} onClose={()=>setShowMembers(false)}/>}</div>
}
function Rule({label,points}:{label:string;points:string}){return <div><span>{label}</span><b>{points}</b></div>}
function QrModal({inviteUrl,onCopy,onClose}:{inviteUrl:string;onCopy:()=>void;onClose:()=>void}){const source=`https://api.qrserver.com/v1/create-qr-code/?size=320x320&margin=12&data=${encodeURIComponent(inviteUrl)}`;return <div className="modal-backdrop" onClick={onClose}><section className="share-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="QR-Code schließen" onClick={onClose}><X size={18}/></button><p className="eyebrow">EINLADUNG SCANNEN</p><h2>Direkt in deine Gruppe</h2><img className="invite-qr" src={source} alt="Scanbarer QR-Code für den Gruppenbeitritt"/><p>Mit der Handy-Kamera scannen oder den Link direkt teilen.</p><button className="primary-button" onClick={onCopy}><Copy size={16}/> Einladungslink kopieren</button></section></div>}
function MembersModal({members,onInvite,onClose}:{members:LiveMember[];onInvite:()=>void;onClose:()=>void}){return <div className="modal-backdrop" onClick={onClose}><section className="share-modal members-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Mitgliederverwaltung schließen" onClick={onClose}><X size={18}/></button><p className="eyebrow">MITGLIEDERVERWALTUNG</p><h2>Deine Testgruppe</h2>{members.map(member=><div className="member manager-member" key={member.user_id}><Jersey type="yellow" small/><strong>{member.profiles?.display_name||'Rider'}</strong><span>{member.role==='admin'?'Admin':'Mitglied'}</span></div>)}<button className="primary-button" onClick={onInvite}><Share2 size={16}/> Freund einladen</button></section></div>}
function CreateGroup({onClose,onCreate}:{onClose:()=>void;onCreate:(name:string)=>void}){const [name,setName]=useState('');const create=()=>{const clean=name.trim();if(clean)onCreate(clean)};return <div className="modal-backdrop group-modal"><section className="create-group"><p className="eyebrow">NEUE PRIVATE GRUPPE</p><h2>Gruppe erstellen</h2><label>Gruppenname<input value={name} placeholder="z. B. Wochenend-Racer" onChange={e=>setName(e.target.value)}/></label><label>Saison<select><option>Saison 2026</option><option>Herbst-Cup 2026</option></select></label><label className="toggle-row"><span>Eintritt nur per Link</span><input type="checkbox" defaultChecked/></label><div><button onClick={onClose} className="secondary-button">Abbrechen</button><button disabled={!name.trim()} onClick={create} className="primary-button">Erstellen</button></div></section></div>}
