import { useEffect, useState } from 'react'
import { Bike, ChevronRight, Flame, Mountain, Settings, Swords, Trophy, X, Zap } from 'lucide-react'
import { Card, Jersey, SectionHeading } from '../components/Ui'

type JerseyKey = 'yellow' | 'polka' | 'green' | 'white' | 'red' | 'violet'
type ProfileData = { name:string; email:string; height:string; weight:string; gender:string; birthYear:string; team:string }
const profileKey='velo-profile-data'
const defaultProfile:ProfileData={name:'Philipp',email:'philipp@example.com',height:'181',weight:'72',gender:'Männlich',birthYear:'1997',team:'Alpine Cycling Club'}
const jerseys: {type:JerseyKey;title:string;text:string;active?:boolean}[]=[{type:'yellow',title:'Gelbes Trikot',text:'Gesamtwertung · 2.450 PTS',active:true},{type:'polka',title:'Bergtrikot',text:'Bergwertung · 940 PTS'},{type:'green',title:'Sprinttrikot',text:'Sprintwertung · 680 PTS'},{type:'white',title:'Young Rider',text:'Erste VELO-LEAGUE-Saison'},{type:'red',title:'Form der Woche',text:'Beste 7-Tage-Punkteausbeute'},{type:'violet',title:'Form des Monats',text:'Beste 30-Tage-Punkteausbeute'}]
const history: Record<JerseyKey,{name:string;from:string;to:string;days:number;reason:string}[]>={yellow:[{name:'Philipp',from:'14. Juli 2026',to:'heute',days:15,reason:'Führt mit 140 Punkten vor Max'},{name:'Max',from:'01. Juli 2026',to:'13. Juli 2026',days:13,reason:'Nach Königsetappe übernommen'}],polka:[{name:'Max',from:'07. Juli 2026',to:'heute',days:22,reason:'940 Bergpunkte'}],green:[{name:'Philipp',from:'20. Juli 2026',to:'heute',days:9,reason:'680 Sprintpunkte'}],white:[{name:'Lukas',from:'01. Juli 2026',to:'heute',days:29,reason:'Beste erste Saison'}],red:[{name:'Thomas',from:'25. Juli 2026',to:'heute',days:4,reason:'530 Punkte in den letzten 7 Tagen'}],violet:[{name:'Philipp',from:'01. Juli 2026',to:'heute',days:29,reason:'1.240 Punkte in den letzten 30 Tagen'}]}
const goals:Record<JerseyKey,string>={yellow:'141 Saisonpunkte vor Max bleiben.',polka:'720 Höhenmeter mehr als Max sammeln.',green:'3 Sprintpunkte bis zur Führung holen.',white:'18 Saisonpunkte vor Lukas in der Young-Rider-Wertung.',red:'96 Punkte in den nächsten 7 Tagen erzielen.',violet:'410 Punkte bis Monatsende aufholen.'}
const badges=[{icon:Mountain,title:'Bergziege',text:'10.000 hm in einer Saison',tone:'yellow'},{icon:Flame,title:'5 Siege Serie',text:'Unaufhaltsam seit Mai',tone:'red'},{icon:Bike,title:'5000 km Fahrer',text:'Dem Ziel ganz nah',tone:'green'},{icon:Zap,title:'Form der Woche',text:'Höchste Punkteausbeute',tone:'yellow'},{icon:Swords,title:'Duell-Champion',text:'4 direkte Siege',tone:'red'},{icon:Trophy,title:'Attacke der Woche',text:'+180 Punkte an einem Tag',tone:'green'}]

export function Profile(){const [selected,setSelected]=useState<JerseyKey>('yellow');const [profile,setProfile]=useState<ProfileData>(defaultProfile);const [settings,setSettings]=useState(false);useEffect(()=>{const saved=localStorage.getItem(profileKey);if(saved)setProfile({...defaultProfile,...JSON.parse(saved)})},[]);const current=jerseys.find(j=>j.type===selected)!;return <div className="page"><Card className="profile-hero"><button aria-label="Profileinstellungen öffnen" onClick={()=>setSettings(true)} className="profile-settings"><Settings size={18}/></button><div className="profile-avatar">{profile.name.slice(0,1).toUpperCase()}</div><div><p className="eyebrow">{profile.team.toUpperCase()}</p><h2>{profile.name}</h2><p>Elite Rider · Level 42</p></div><div className="profile-level"><strong>4.820</strong><span>XP bis Level 43</span><i><b/></i></div></Card><SectionHeading eyebrow="DEINE WERTUNGEN" title="Trikots"/><div className="jersey-shelf">{jerseys.map(j=><button key={j.title} onClick={()=>setSelected(j.type)} className={selected===j.type?'jersey-card active':'jersey-card'}><Jersey type={j.type}/><div><strong>{j.title}</strong><span>{j.text}</span></div>{j.active&&<em>FÜHRT</em>}</button>)}</div><Card className="jersey-target"><div><p className="eyebrow">NÄCHSTES TRIKOT-ZIEL</p><h3><Jersey type={current.type} small/>{current.title}</h3><p>{goals[selected]}</p></div><span>Live-Wertung</span></Card><Card className="jersey-history"><div className="history-header"><Jersey type={current.type} small/><div><p className="eyebrow">TRIKOT-HISTORIE</p><h3>{current.title}</h3></div><span>{history[selected].length} Wechsel</span></div><div className="history-table">{history[selected].map((entry,index)=><div className="timeline-row" key={`${entry.name}-${entry.from}`}><span className="timeline-dot">{index+1}</span><div><strong>{entry.name}</strong><p>{entry.from} — {entry.to}</p><small>{entry.reason}</small></div><b>{entry.days} {entry.days===1?'Tag':'Tage'}</b></div>)}</div></Card><SectionHeading eyebrow="PERSÖNLICHE BESTENLISTE" title="Abzeichen"/><div className="achievement-grid">{badges.map(b=>{const Icon=b.icon;return <Card key={b.title} className="achievement"><span className={b.tone}><Icon/></span><strong>{b.title}</strong><p>{b.text}</p></Card>})}</div><SectionHeading eyebrow="SAISON 2026" title="Gesamte Saisonhistorie"/><Card className="history"><div><span className="history-date">JULI 2026</span><Jersey/><strong>Gelbes Trikot</strong><small>Gesamtwertung · 2.450 PTS</small></div><ChevronRight size={18}/><div><span className="history-date">JUNI 2026</span><Jersey type="polka"/><strong>Bergtrikot</strong><small>Bergwertung · 940 PTS</small></div></Card>{settings&&<ProfileSettings initial={profile} onClose={()=>setSettings(false)} onSave={value=>{setProfile(value);localStorage.setItem(profileKey,JSON.stringify(value));setSettings(false)}}/>}</div>}
function ProfileSettings({initial,onClose,onSave}:{initial:ProfileData;onClose:()=>void;onSave:(value:ProfileData)=>void}){const [form,setForm]=useState(initial);const update=(key:keyof ProfileData,value:string)=>setForm(current=>({...current,[key]:value}));return <div className="modal-backdrop profile-settings-backdrop" onClick={onClose}><section className="profile-settings-modal" onClick={event=>event.stopPropagation()}><button className="modal-close" aria-label="Einstellungen schließen" onClick={onClose}><X size={18}/></button><p className="eyebrow">PROFIL & KÖRPERDATEN</p><h2>Deine Einstellungen</h2><p className="settings-intro">Diese Angaben bleiben auf diesem Gerät gespeichert und sind nur für deine Gruppe gedacht.</p><div className="settings-fields"><label>Name<input value={form.name} onChange={event=>update('name',event.target.value)} /></label><label>E-Mail-Adresse<input type="email" value={form.email} onChange={event=>update('email',event.target.value)} /></label><label>Größe (cm)<input inputMode="numeric" value={form.height} onChange={event=>update('height',event.target.value)} /></label><label>Gewicht (kg)<input inputMode="decimal" value={form.weight} onChange={event=>update('weight',event.target.value)} /></label><label>Geschlecht<select value={form.gender} onChange={event=>update('gender',event.target.value)}><option>Männlich</option><option>Weiblich</option><option>Divers</option><option>Möchte ich nicht angeben</option></select></label><label>Geburtsjahr<input inputMode="numeric" value={form.birthYear} onChange={event=>update('birthYear',event.target.value)} /></label><label className="settings-wide">Team / Club<input value={form.team} onChange={event=>update('team',event.target.value)} /></label></div><div className="settings-actions"><button className="secondary-button" onClick={onClose}>Abbrechen</button><button className="primary-button" onClick={()=>onSave(form)}>Speichern</button></div></section></div>}
