import { useEffect, useMemo, useState } from 'react'
import { CalendarCheck2, ChevronLeft, ChevronRight, Flag, Mountain, X, Zap } from 'lucide-react'
import { Card, SectionHeading } from '../components/Ui'
type Event = { id: string; date: string; title: string; type: string; end: string; segment: string }
const key='velo-test-events',startDate=new Date('2026-07-29T12:00:00'),finalDate='2026-10-01'
const makeDays=(offset:number)=>Array.from({length:7},(_,index)=>{const date=new Date(startDate);date.setDate(date.getDate()+offset*7+index);return{date,key:date.toISOString().slice(0,10),day:String(date.getDate()).padStart(2,'0'),week:date.toLocaleDateString('de-DE',{weekday:'short'}).replace('.',''),month:date.toLocaleDateString('de-DE',{month:'short'}).toUpperCase()}})
export function SeasonCalendar({notify}:{notify:(message:string)=>void}){const[events,setEvents]=useState<Event[]>([]),[weekOffset,setWeekOffset]=useState(0),[selectedDay,setSelectedDay]=useState<ReturnType<typeof makeDays>[number]|null>(null),[selected,setSelected]=useState<Event|null>(null),[finalOpen,setFinalOpen]=useState(false);const days=useMemo(()=>makeDays(weekOffset),[weekOffset]);useEffect(()=>{const saved=localStorage.getItem(key);if(saved)setEvents(JSON.parse(saved))},[]);const label=`${days[0].date.toLocaleDateString('de-DE',{month:'long'})} — ${days[6].date.toLocaleDateString('de-DE',{month:'long',year:'numeric'})}`,dayEvents=selectedDay?events.filter(event=>event.date===selectedDay.key):[];return <div className="page"><div className="calendar-head"><button className="icon-button" onClick={()=>setWeekOffset(current=>current-1)}><ChevronLeft size={18}/></button><div><p className="eyebrow">SAISON 2026</p><h2>{label}</h2></div><button className="icon-button" onClick={()=>setWeekOffset(current=>current+1)}><ChevronRight size={18}/></button></div><Card className="calendar-strip">{days.map((day,index)=>{const has=events.some(event=>event.date===day.key);return <button onClick={()=>setSelectedDay(day)} className={`${weekOffset===0&&index===0?'today-card':'calendar-day'} ${has?'planned-day':''}`} key={day.key}><span>{weekOffset===0&&index===0?'HEUTE':day.week}</span><b>{day.day}</b><small>{day.month}</small>{has&&<i/>}</button>})}</Card><SectionHeading eyebrow="DEINE NÄCHSTEN ZIELE" title="Rennkalender"/>{events.length===0?<Card className="empty-inline"><CalendarCheck2 size={20}/><div><strong>Dein Kalender ist noch frei.</strong><p>Geplante oder angenommene Challenges erscheinen automatisch hier.</p></div></Card>:<div className="event-list">{events.map(event=><EventCard event={event} onClick={()=>setSelected(event)} key={event.id}/>)}</div>}<button className="event-button" onClick={()=>setFinalOpen(true)}><Card className="season-progress"><CalendarCheck2 size={20}/><div><strong>Saisonfinale in 64 Tagen</strong><p>Tippe für Datum und Saisonabschluss-Infos.</p></div><ChevronRight size={18}/></Card></button>{selectedDay&&<DayDetail day={selectedDay} events={dayEvents} onClose={()=>setSelectedDay(null)} onSelect={setSelected}/>} {selected&&<EventDetail event={selected} onClose={()=>setSelected(null)} notify={notify}/>} {finalOpen&&<FinalDetail onClose={()=>setFinalOpen(false)}/>}</div>}
function EventCard({event,onClick}:{event:Event;onClick:()=>void}){const date=new Date(`${event.date}T12:00:00`);return <button onClick={onClick} className="event-button"><Card className="event-card"><div className="event-date"><b>{String(date.getDate()).padStart(2,'0')}</b><span>{date.toLocaleDateString('de-DE',{month:'short'}).toUpperCase()}</span></div><span className="event-icon yellow"><Mountain size={19}/></span><div><h3>{event.title}</h3><p>{event.type} · endet {event.end}</p></div><ChevronRight size={18}/></Card></button>}
function DayDetail({day,events,onClose,onSelect}:{day:ReturnType<typeof makeDays>[number];events:Event[];onClose:()=>void;onSelect:(event:Event)=>void}){return <div className="modal-backdrop planner-wrap"><section className="planner-card"><button className="drawer-close" onClick={onClose}><X size={19}/></button><p className="eyebrow">{day.week.toUpperCase()} · {day.day}. {day.month}</p><h2>Tagesübersicht</h2>{events.length===0?<p className="empty-copy">Für diesen Tag ist noch nichts geplant.</p>:events.map(event=><button className="day-event" key={event.id} onClick={()=>{onClose();onSelect(event)}}><Flag size={17}/><span><b>{event.title}</b><small>{event.segment} · {event.type}</small></span><ChevronRight size={16}/></button>)}</section></div>}
function EventDetail({event,onClose,notify}:{event:Event;onClose:()=>void;notify:(message:string)=>void}){return <div className="modal-backdrop planner-wrap"><section className="planner-card"><button className="drawer-close" onClick={onClose}><X size={19}/></button><p className="eyebrow">GEPLANTE CHALLENGE</p><h2>{event.title}</h2><div className="challenge-insights"><div><span>Segment</span><b>{event.segment}</b></div><div><span>Gegner</span><b>Max</b></div><div><span>Endet</span><b>{event.end}</b></div><div><span>Belohnung</span><b>150 PTS</b></div></div><button onClick={()=>{notify('Challenge-Details geöffnet.');onClose()}} className="primary-button wide"><Zap size={16}/> Verstanden</button></section></div>}
function FinalDetail({onClose}:{onClose:()=>void}){return <div className="modal-backdrop planner-wrap"><section className="planner-card"><button className="drawer-close" onClick={onClose}><X size={19}/></button><p className="eyebrow">SAISONABSCHLUSS 2026</p><h2>Saisonfinale</h2><div className="challenge-insights"><div><span>Datum</span><b>01. Oktober 2026</b></div><div><span>Uhrzeit</span><b>20:00 Uhr</b></div><div><span>Ort</span><b>In deiner Gruppe</b></div><div><span>Wertung</span><b>Alle Trikots</b></div></div><p className="empty-copy">Nach dem Ende werden Rangliste, Trikot-Historie und Abzeichen der Saison festgeschrieben.</p></section></div>}
