import { useMemo, useState } from 'react'
import { ArrowRight, Bike, Check, LockKeyhole, Mail, ShieldCheck, UserPlus } from 'lucide-react'
import { isSupabaseConfigured, resendSignupOtp, signInWithSupabase, signUpWithSupabase, verifyEmailOtp } from '../lib/supabaseAuth'

type Account = { email: string; password: string; name: string }
type PendingAccount = { email: string; name: string }
const accountKey = 'velo-test-account'
const sessionKey = 'velo-session'
export function getStoredSession() { return localStorage.getItem(sessionKey) ?? sessionStorage.getItem(sessionKey) }

export function AuthGate({ onAuthenticated }: { onAuthenticated: (name: string) => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login'), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [name, setName] = useState(''), [remember, setRemember] = useState(true), [pending, setPending] = useState<PendingAccount | null>(null), [otp, setOtp] = useState(''), [error, setError] = useState(''), [message, setMessage] = useState(''), [loading, setLoading] = useState(false)
  const rules = useMemo(() => [{ label: 'Mindestens 8 Zeichen', met: password.length >= 8 }, { label: 'Mindestens ein Großbuchstabe', met: /[A-ZÄÖÜ]/.test(password) }, { label: 'Mindestens eine Zahl', met: /\d/.test(password) }], [password])
  const start = (displayName: string) => { if (remember) localStorage.setItem(sessionKey, displayName); else sessionStorage.setItem(sessionKey, displayName); onAuthenticated(displayName) }
  const submit = async () => { const cleanEmail = email.trim().toLowerCase(); if (!cleanEmail || !password || (mode === 'register' && !name.trim())) return setError('Bitte fülle alle Felder aus.'); if (mode === 'register' && !rules.every(rule => rule.met)) return setError('Bitte erfülle alle Passwortanforderungen.'); setLoading(true); setError(''); if (isSupabaseConfigured) { const result = mode === 'register' ? await signUpWithSupabase(cleanEmail, password, name.trim()) : await signInWithSupabase(cleanEmail, password); setLoading(false); if (result.error) return setError(result.error.message || 'Anmeldung nicht möglich.'); if (mode === 'register') { setPending({ email: cleanEmail, name: name.trim() }); setOtp(''); return } const displayName = result.user?.user_metadata?.display_name || result.user?.email?.split('@')[0] || 'Rider'; localStorage.setItem('velo-new-user', 'true'); start(displayName); return } setLoading(false); if (mode === 'register') { const account: Account = { email: cleanEmail, password, name: name.trim() }; localStorage.setItem(accountKey, JSON.stringify(account)); localStorage.setItem('velo-new-user', 'true'); start(account.name); return } const raw = localStorage.getItem(accountKey), account = raw ? JSON.parse(raw) as Account : null; if (!account || account.email !== cleanEmail || account.password !== password) return setError('E-Mail-Adresse oder Passwort stimmen nicht.'); start(account.name) }
  const verify = async () => { if (otp.length !== 6) return setError('Bitte gib den 6-stelligen Code ein.'); setLoading(true); setError(''); const result = await verifyEmailOtp(pending!.email, otp); setLoading(false); if (result.error) return setError(result.error.message || 'Der Code ist ungültig oder abgelaufen.'); localStorage.setItem('velo-new-user', 'true'); start(result.user?.user_metadata?.display_name || pending!.name) }
  const resend = async () => { setLoading(true); setError(''); const result = await resendSignupOtp(pending!.email); setLoading(false); if (result.error) return setError(result.error.message || 'Code konnte nicht erneut gesendet werden.'); setMessage('Ein neuer Code wurde gesendet.') }
  const demo = () => { localStorage.removeItem('velo-new-user'); localStorage.setItem(sessionKey, 'Philipp'); onAuthenticated('Philipp') }
  if (pending) return <main className="auth-page"><section className="auth-panel"><Brand/><p className="eyebrow">E-MAIL BESTÄTIGEN</p><h1>Dein Code ist unterwegs.</h1><p className="auth-copy">Wir haben einen 6-stelligen Bestätigungscode an <b>{pending.email}</b> gesendet.</p><form className="auth-form" onSubmit={event => { event.preventDefault(); void verify() }}><label>Bestätigungscode<div><ShieldCheck size={16}/><input className="otp-input" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={otp} onChange={event => setOtp(event.target.value.replace(/\D/g, ''))} placeholder="000000" autoFocus/></div></label>{error && <p className="auth-error">{error}</p>}{message && <p className="auth-success"><ShieldCheck size={15}/>{message}</p>}<button className="auth-submit" disabled={loading} type="submit">{loading ? 'Bitte warten…' : <>Code bestätigen <ArrowRight size={17}/></>}</button></form><div className="developer-entry"><span>Keinen Code erhalten?</span><button disabled={loading} type="button" onClick={() => void resend()}>Code erneut senden</button><button type="button" onClick={() => { setPending(null); setMessage(''); setError('') }}>E-Mail-Adresse ändern</button></div></section></main>
  return <main className="auth-page"><section className="auth-panel"><Brand/><p className="eyebrow">PRIVATE CYCLING LEAGUES</p><h1>{mode === 'login' ? 'Willkommen zurück.' : 'Deine Saison beginnt hier.'}</h1><p className="auth-copy">{isSupabaseConfigured ? 'Dein Zugang wird sicher über VELO LEAGUE gespeichert.' : 'Private Testversion auf diesem Gerät.'}</p><div className="auth-tabs"><button className={mode === 'login' ? 'active' : ''} onClick={() => { setMode('login'); setError(''); setMessage('') }}>Anmelden</button><button className={mode === 'register' ? 'active' : ''} onClick={() => { setMode('register'); setError(''); setMessage('') }}>Registrieren</button></div><form className="auth-form" onSubmit={event => { event.preventDefault(); void submit() }}>{mode === 'register' && <label>Name<div><UserPlus size={16}/><input autoComplete="name" value={name} onChange={event => setName(event.target.value)} placeholder="Dein Name"/></div></label>}<label>E-Mail-Adresse<div><Mail size={16}/><input type="email" autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="name@email.de"/></div></label><label>Passwort<div><LockKeyhole size={16}/><input type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} value={password} onChange={event => setPassword(event.target.value)} placeholder="Dein Passwort"/></div></label>{mode === 'register' && <div className="password-requirements">{rules.map(rule => <span className={rule.met ? 'met' : ''} key={rule.label}><i>{rule.met && <Check size={12}/>}</i>{rule.label}</span>)}</div>}<label className="remember-row"><input type="checkbox" checked={remember} onChange={event => setRemember(event.target.checked)}/><span>Angemeldet bleiben</span></label>{error && <p className="auth-error">{error}</p>}{message && <p className="auth-success"><ShieldCheck size={15}/>{message}</p>}<button className="auth-submit" disabled={loading} type="submit">{loading ? 'Bitte warten…' : mode === 'login' ? <>Anmelden <ArrowRight size={17}/></> : <>Konto erstellen <ArrowRight size={17}/></>}</button></form><div className="developer-entry"><span>Nur zum Testen</span><button type="button" onClick={demo}>Entwickler-Demo starten <ArrowRight size={15}/></button></div></section></main>
}
function Brand() { return <div className="auth-brand"><span><Bike size={21}/></span><strong>VELO <b>LEAGUE</b></strong></div> }
