import { X, Flame, Mountain, Trophy, TrendingUp, Zap } from 'lucide-react'
import { Card, Jersey } from './Ui'

const stats: Record<string, { points: string; rank: string; color: string; km: string; wins: string }> = { Philipp: { points: '2.450', rank: '#1', color: 'yellow', km: '1.850', wins: '14' }, Max: { points: '2.310', rank: '#2', color: 'polka', km: '1.730', wins: '11' }, Thomas: { points: '2.100', rank: '#3', color: 'plain', km: '1.710', wins: '7' }, Lukas: { points: '1.950', rank: '#4', color: 'plain', km: '1.540', wins: '5' } }
const formData: Record<string, { day: string; points: number }[]> = { Philipp: [{ day: 'Do', points: 46 }, { day: 'Fr', points: 78 }, { day: 'Sa', points: 58 }, { day: 'So', points: 92 }, { day: 'Mo', points: 74 }, { day: 'Di', points: 103 }, { day: 'Heute', points: 112 }], Max: [{ day: 'Do', points: 61 }, { day: 'Fr', points: 52 }, { day: 'Sa', points: 88 }, { day: 'So', points: 69 }, { day: 'Mo', points: 95 }, { day: 'Di', points: 81 }, { day: 'Heute', points: 106 }], Thomas: [{ day: 'Do', points: 38 }, { day: 'Fr', points: 64 }, { day: 'Sa', points: 48 }, { day: 'So', points: 75 }, { day: 'Mo', points: 62 }, { day: 'Di', points: 84 }, { day: 'Heute', points: 91 }], Lukas: [{ day: 'Do', points: 31 }, { day: 'Fr', points: 47 }, { day: 'Sa', points: 55 }, { day: 'So', points: 40 }, { day: 'Mo', points: 73 }, { day: 'Di', points: 68 }, { day: 'Heute', points: 79 }] }

export function RiderDetail({ name, onClose }: { name: string; onClose: () => void }) {
  const rider = stats[name]
  const form = formData[name] ?? formData.Philipp
  const weeklyPoints = form.reduce((sum, item) => sum + item.points, 0)
  const average = Math.round(weeklyPoints / form.length)
  const highest = Math.max(...form.map(item => item.points))
  return <div className="modal-backdrop" onClick={onClose}><aside className="rider-drawer" onClick={event => event.stopPropagation()}><button className="drawer-close" aria-label="Profil schließen" onClick={onClose}><X size={20}/></button><div className="drawer-profile"><Jersey type={rider.color}/><div><p className="eyebrow">ALPINE CYCLING LEAGUE</p><h2>{name}</h2><span>{rider.rank} Gesamtwertung</span></div></div><div className="drawer-points"><strong>{rider.points}</strong><span>Saisonpunkte</span></div><div className="drawer-stats"><span><Mountain size={16}/><b>28.400</b> hm</span><span><Zap size={16}/><b>{rider.km}</b> km</span><span><Trophy size={16}/><b>{rider.wins}</b> Siege</span></div><div className="form-title"><h3>Aktuelle Form</h3><span>Letzte 7 Tage</span></div><div className="form-summary"><div><TrendingUp size={17}/><span>Formindex</span><b>{Math.min(99, Math.round(average * 1.03))}<small>/100</small></b></div><div><Flame size={17}/><span>Wochenpunkte</span><b>{weeklyPoints}</b></div><div><Trophy size={17}/><span>Bester Tag</span><b>{highest} <small>PTS</small></b></div></div><p className="chart-explanation">Tagespunkte aus Fahrten, Segmenten und Challenges – klar nach Tag aufgeschlüsselt.</p><div className="form-list">{form.map(item => <div key={item.day}><span>{item.day}</span><i><b style={{ width: `${item.points / 1.2}%` }}/></i><strong>{item.points} PTS</strong></div>)}</div><Card className="head-to-head"><Flame size={18}/><div><b>Direktes Duell mit Philipp</b><p>Philipp 4 · {name === 'Philipp' ? '4' : '3'} {name}</p></div></Card></aside></div>
}
