export function getOrigin(req) { const host = String(req.headers?.['x-forwarded-host'] || req.headers?.host || '').split(',')[0]; const proto = String(req.headers?.['x-forwarded-proto'] || 'https').split(',')[0]; return `${proto}://${host}` }
export function getAppOrigin(req) { return (process.env.STRAVA_APP_ORIGIN || getOrigin(req)).replace(/\/$/, '') }
export function cookies(req) { const raw = String(req.headers?.cookie || ''); return Object.fromEntries(raw.split(';').map(part => { const divider = part.indexOf('='); return divider === -1 ? [part.trim(), ''] : [part.slice(0, divider).trim(), decodeURIComponent(part.slice(divider + 1))] }).filter(([name]) => name)) }
export function cookie(name, value, maxAge, path = '/api/strava') { return `${name}=${encodeURIComponent(value)}; Path=${path}; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax` }
export function clearCookie(name, path = '/api/strava') { return cookie(name, '', 0, path) }
export function appendCookies(res, values) { res.setHeader('Set-Cookie', values) }
export async function exchangeToken(params) { const body = new URLSearchParams({ client_id: process.env.STRAVA_CLIENT_ID || '', client_secret: process.env.STRAVA_CLIENT_SECRET || '', ...params }); const response = await fetch('https://www.strava.com/oauth/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); if (!response.ok) throw new Error('Strava konnte die Verbindung nicht bestätigen.'); return response.json() }
export function tokenCookies(tokens) { const lifetime = 60 * 60 * 24 * 180; return [cookie('velo_strava_access', tokens.access_token, Math.max(60, tokens.expires_at - Math.floor(Date.now() / 1000))), cookie('velo_strava_refresh', tokens.refresh_token, lifetime), cookie('velo_strava_expires', String(tokens.expires_at), lifetime)] }
export function configured() { return Boolean(process.env.STRAVA_CLIENT_ID && process.env.STRAVA_CLIENT_SECRET) }
export async function authenticatedUser(req) { const token=String(req.headers?.authorization||'').replace(/^Bearer\s+/i,''); if(!token||!process.env.VITE_SUPABASE_URL||!(process.env.VITE_SUPABASE_ANON_KEY||process.env.VITE_SUPABASE_PUBLISHABLE_KEY)) return null; const response=await fetch(`${process.env.VITE_SUPABASE_URL}/auth/v1/user`,{headers:{apikey:process.env.VITE_SUPABASE_ANON_KEY||process.env.VITE_SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`}}); return response.ok?response.json():null }
